### PR TITLE
improve FFS efficiency

### PR DESCRIPTION
**Pull request by hz-xiaxz**
small improvement by adding "view"

### CODE REVIEW

**Comment by hz-xiaxz** [comment]
```julia
U = randn(2^20,20)
@btime FFS($U)
```
before `823.374 ms (335 allocations: 2.26 GiB)`
now `640.850 ms (333 allocations: 792.31 MiB)`
tested on my poor laptop

**Comment by hz-xiaxz** [comment]
tested on the server:
```julia
julia> U = randn(2^20,20)
julia> @btime FFS($U)
  862.935 ms (333 allocations: 792.31 MiB)
julia> @profile for i in 1:10 FFS(U) end
julia> Profile.print(;format=:flat)
...
 4250         0 …Sampling/src/FFS.jl    18 FFS(u::Matrix{Float64})
   483         0 …Sampling/src/FFS.jl    19 FFS(u::Matrix{Float64})
    10         0 …Sampling/src/FFS.jl    24 FFS(u::Matrix{Float64})
     2         0 …Sampling/src/FFS.jl    26 FFS(u::Matrix{Float64})
   453         0 …Sampling/src/FFS.jl    28 FFS(u::Matrix{Float64})
    26         0 …Sampling/src/FFS.jl    29 FFS(u::Matrix{Float64})
...
```

It seems like that the efficiency bottleneck is at `line 18` and mostly contributed by `mul!`. I suggest that there's no more need to optimize, since `mul!` is fast enough.
image
@GiggleLiu Do you have any suggestion?

**Comment by GiggleLiu** [comment]
Comment:
using view may decrease the matrix multiplication performance, e.g.
```julia
julia> @btime FFS($U);
  296.104 ms (333 allocations: 792.31 MiB)
```

After making the following change:
```julia
prob = abs2.((view(U, :, 1:i) * n_vec)[avail])
# prob = abs2.(view(U, avail, 1:i) * n_vec)
```
We have
```julia
julia> @btime FFS($U)
  185.361 ms (333 allocations: 792.31 MiB)
1048576-element BitVector:
```

**Comment by hz-xiaxz** [comment]
Thanks! I was just curious about why this multiplication doesn't invoke BLAS(I saw it use Julia's generic_matvecmul! from profiling)

**Comment by GiggleLiu** [comment]
> Thanks! I was just curious about why this multiplication doesn't invoke BLAS(I saw it use Julia's generic_matvecmul! from profiling)

only arrays that continguous in memory can call BLAS.

**Pull request merged**
